name: Run Test Cases
  run: |
    set -e

    for file in tests/input*.txt; do
      num=$(basename "$file" .txt | sed 's/input//')

      ./main < "$file" > actual.txt

      # remove Windows line endings
      tr -d '\r' < actual.txt > a.txt
      tr -d '\r' < "tests/expected${num}.txt" > e.txt

      echo "Running test $num"

      echo "Actual:"
      cat -A a.txt

      echo "Expected:"
      cat -A e.txt

      diff -u a.txt e.txt
    done